export const EXPERTS = [
  {
    id: 'kofi-asante',
    initials: 'KA',
    name: 'Kofi Asante',
    role: 'Avocat · Droit des sociétés OHADA',
    location: 'Abidjan, Côte d\'Ivoire',
    plan: 'premium',
    verified: true,
    available: true,
    rating: 4.9,
    reviews: 127,
    missions: 127,
    experience: 15,
    successRate: 98,
    responseTime: '< 2h',
    countries: 6,
    profileViews: 1240,
    rate: '250 000 FCFA',
    ratePeriod: '/consultation',
    bio: 'Avocat au Barreau d\'Abidjan depuis 2009, spécialisé en droit des affaires OHADA. Mon cabinet intervient sur l\'ensemble des problématiques liées à la création, structuration et restructuration des entreprises dans la zone UEMOA et au-delà.',
    skills: ['Droit des sociétés', 'OHADA', 'Fusions-acquisitions', 'Arbitrage CCJA', 'Contrats commerciaux', 'Restructuration', 'Droit bancaire'],
    languages: [{ name: 'Français', level: 'Natif' }, { name: 'Anglais', level: 'Courant' }, { name: 'Twi', level: 'Natif' }],
    domains: ['Droit des sociétés', 'Fusions-acquisitions', 'Arbitrage CCJA'],
    reviews_list: [
      { author: 'Diallo Kouyaté', company: 'DG · TechSen SARL', date: 'Nov. 2024', rating: 5, text: 'Excellent travail sur notre contrat de distribution. Maître Asante a su identifier tous les risques OHADA et proposer des clauses de protection efficaces. Je recommande vivement.' },
      { author: 'Marie-Berthe Ouédraogo', company: 'DAF · Finserv BF', date: 'Oct. 2024', rating: 5, text: 'Très professionnel, réactif et pédagogue. Il a pris le temps d\'expliquer chaque aspect du dossier d\'arbitrage. Résultat favorable obtenu en 3 mois.' },
    ],
    projects: [
      { title: 'Contrat de distribution UEMOA', client: 'Logistics SA', date: 'Nov. 2024', status: 'done' },
      { title: 'Restructuration société anonyme', client: 'AgriCo SARL', date: 'En cours', status: 'active' },
      { title: 'Arbitrage CCJA — Litige commercial', client: 'Confidentiel', date: 'Oct. 2024', status: 'review' },
    ],
  },
  {
    id: 'fatou-sow',
    initials: 'FS',
    name: 'Fatou Sow',
    role: 'Expert-Comptable agréée · SYSCOHADA révisé',
    location: 'Dakar, Sénégal',
    plan: 'spotlight',
    verified: true,
    available: true,
    rating: 4.8,
    reviews: 84,
    missions: 84,
    experience: 12,
    successRate: 97,
    responseTime: '< 4h',
    countries: 6,
    rate: '180 000 FCFA',
    ratePeriod: '/consultation',
    bio: 'Commissaire aux comptes agréée avec 12 ans d\'expérience. Accompagnement SYSCOHADA révisé pour les PME à travers 6 pays OHADA. Spécialiste de la mise en conformité comptable.',
    skills: ['SYSCOHADA révisé', 'Audit légal', 'Commissaire aux comptes', 'Fiscalité OHADA', 'PME/PMI', 'Consolidation'],
    languages: [{ name: 'Français', level: 'Natif' }, { name: 'Wolof', level: 'Natif' }, { name: 'Anglais', level: 'Intermédiaire' }],
    domains: ['SYSCOHADA', 'Audit légal', 'Comptabilité PME'],
  },
  {
    id: 'aminata-mbaye',
    initials: 'AM',
    name: 'Aminata Mbaye',
    role: 'Consultante RH · Droit du travail OHADA',
    location: 'Dakar, Sénégal',
    plan: 'pro',
    verified: true,
    available: false,
    rating: 4.7,
    reviews: 56,
    missions: 56,
    experience: 8,
    successRate: 95,
    responseTime: '< 8h',
    countries: 4,
    rate: '120 000 FCFA',
    ratePeriod: '/consultation',
    bio: 'Spécialiste droit du travail OHADA et gestion RH pour PME. Basée à Dakar, interventions dans l\'espace UEMOA.',
    skills: ['Droit du travail', 'CDI / CDD', 'Gestion RH', 'Négociation', 'Licenciement'],
    languages: [{ name: 'Français', level: 'Natif' }, { name: 'Wolof', level: 'Natif' }],
    domains: ['Droit du travail', 'Gestion RH'],
  },
]

export const CURRENT_USER = {
  id: 'kofi-asante',
  initials: 'KA',
  name: 'Kofi Asante',
  plan: 'premium',
  verified: true,
}

export const NOTIFICATIONS = [
  { id: 1, type: 'message',  text: 'Nouveau message de Diallo Kouyaté concernant la restructuration.',  time: 'Il y a 20 min',   dot: 'gold',  unread: true },
  { id: 2, type: 'payment',  text: 'Paiement reçu — 250 000 FCFA (dossier arbitrage)',                  time: 'Il y a 2h',     dot: 'green', unread: true },
  { id: 3, type: 'request',  text: 'Nouvelle demande : Contrat bail commercial — Marie Ouédraogo',      time: 'Hier 16h30',    dot: 'navy',  unread: false },
  { id: 4, type: 'review',   text: 'Nouvel avis 5 étoiles de FoodGroup CI',                             time: 'Hier 14h12',    dot: 'green', unread: false },
  { id: 5, type: 'view',     text: 'Votre profil a été consulté 47 fois aujourd\'hui',                  time: 'Aujourd\'hui 09h', dot: 'gold', unread: false },
]

export const PROJECTS = [
  { id: 1, title: 'Restructuration société anonyme',      client: 'AgriCo SARL',    deadline: '28 jan.',  progress: 65, status: 'active' },
  { id: 2, title: 'Arbitrage CCJA — Litige commercial',   client: 'Confidentiel',   deadline: '25 jan.',  progress: 88, status: 'review' },
  { id: 3, title: 'Contrat de franchise UEMOA',           client: 'FoodGroup CI',   deadline: '10 fév.',  progress: 22, status: 'active' },
]

export const CONVERSATIONS = [
  { id: 1, name: 'Diallo Kouyaté',       initials: 'DK', preview: 'Merci pour les précisions sur le contrat…', time: '20min', unread: 3, online: true },
  { id: 2, name: 'Marie-Berthe Ouédraogo', initials: 'MB', preview: 'Document bien reçu, je reviens vers vous',  time: '2h',    unread: 1, online: false },
  { id: 3, name: 'Fatou Sow',            initials: 'FS', preview: 'Collaboration SYSCOHADA — intéressée',        time: 'Hier',  unread: 0, online: false },
  { id: 4, name: 'FoodGroup CI',         initials: 'FG', preview: 'Contrat franchise — suite à donner',          time: 'Lun.',  unread: 0, online: false },
  { id: 5, name: 'TechSen SARL',         initials: 'TC', preview: 'Merci pour l\'avis ! Excellent travail.',     time: 'Sam.',  unread: 0, online: false },
]

export const DOMAINS = [
  { label: 'Droit des sociétés' },
  { label: 'SYSCOHADA' },
  { label: 'Droit du travail' },
  { label: 'Arbitrage CCJA' },
  { label: 'Contrats' },
  { label: 'Création entreprise' },
]

export const ROLES = [
  { name: 'Avocat / Juriste',   desc: 'Barreau, conseil juridique',   value: 'lawyer' },
  { name: 'Expert-Comptable',   desc: 'SYSCOHADA, audit, fiscalité',  value: 'accountant' },
  { name: 'Consultant OHADA',   desc: 'Conseils, formations',         value: 'consultant' },
  { name: 'Entreprise / PME',   desc: 'DAF, DG, RH',                 value: 'company' },
  { name: 'Consultant RH',      desc: 'Droit du travail, RH',         value: 'hr' },
  { name: 'Étudiant en droit',  desc: 'Master, doctorat OHADA',       value: 'student' },
]

export const PRICING_PLANS = [
  {
    name: 'Free',
    price: '0 €',
    period: '/mois · Pour démarrer',
    features: [
      { ok: true,  text: 'Profil public basique' },
      { ok: true,  text: '3 recherches / jour' },
      { ok: true,  text: '1 dossier actif' },
      { ok: false, text: 'IA OHADA illimitée' },
      { ok: false, text: 'Badge vérifié' },
      { ok: false, text: 'Paiement escrow' },
    ],
    cta: 'Commencer',
    ctaStyle: 'outline',
  },
  {
    name: 'Pro',
    price: '29 €',
    period: '/mois · Professionnel',
    features: [
      { ok: true,  text: 'Profil complet + badge vérifié' },
      { ok: true,  text: 'Recherches illimitées' },
      { ok: true,  text: '10 dossiers actifs' },
      { ok: true,  text: 'IA OHADA illimitée' },
      { ok: false, text: 'Priorité résultats' },
      { ok: false, text: 'Analytics profil' },
    ],
    cta: 'Choisir Pro',
    ctaStyle: 'navy',
  },
  {
    name: 'Premium',
    price: '79 €',
    period: '/mois · Expert référencé',
    featured: true,
    features: [
      { ok: true, text: 'Profil complet + badge vérifié' },
      { ok: true, text: 'Recherches illimitées' },
      { ok: true, text: 'Dossiers illimités' },
      { ok: true, text: 'IA OHADA illimitée' },
      { ok: true, text: 'Priorité dans résultats' },
      { ok: true, text: 'Analytics profil' },
    ],
    cta: 'Choisir Premium',
    ctaStyle: 'gold',
  },
  {
    name: 'Spotlight',
    price: '149 €',
    period: '/mois · Visibilité max',
    spotlight: true,
    features: [
      { ok: true, text: 'Tout Premium inclus' },
      { ok: true, text: 'Profil mis en lumière' },
      { ok: true, text: 'Top homepage & résultats' },
      { ok: true, text: 'Newsletter Abakoré' },
      { ok: true, text: 'Badge Spotlight' },
      { ok: true, text: 'Compte dédié' },
    ],
    cta: 'Spotlight',
    ctaStyle: 'spotlight',
  },
]
